// Code generated by "stringer -type Support -trimprefix Support"; DO NOT EDIT.

package pmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SupportECG-1]
	_ = x[SupportPPG-2]
	_ = x[SupportAcc-4]
	_ = x[SupportPPI-8]
	_ = x[SupportBioImpedance-16]
	_ = x[SupportGyro-32]
	_ = x[SupportMag-64]
}

const (
	_Support_name_0 = "ECGPPG"
	_Support_name_1 = "Acc"
	_Support_name_2 = "PPI"
	_Support_name_3 = "BioImpedance"
	_Support_name_4 = "Gyro"
	_Support_name_5 = "Mag"
)

var (
	_Support_index_0 = [...]uint8{0, 3, 6}
)

func (i Support) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Support_name_0[_Support_index_0[i]:_Support_index_0[i+1]]
	case i == 4:
		return _Support_name_1
	case i == 8:
		return _Support_name_2
	case i == 16:
		return _Support_name_3
	case i == 32:
		return _Support_name_4
	case i == 64:
		return _Support_name_5
	default:
		return "Support(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
